### ISSUE TITLE
Infografía

### ISSUE THREAD

**Issue by Aylin67** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-Aylin67#1]
[Infografia_Topicos_Avanzados_de.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-Aylin67/files/14528142/Infografia_Topicos_Avanzados_de.pdf)

**Comment by AricelCastro** [comment]
Nuestro equipo a esta infografía le da una calificación de 19/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
